version: "3.7"

services:
  kusamaapi:
    init: true
    stdin_open: true
    container_name: kusamaapi
    tty: true
    image: 406746673604.dkr.ecr.us-east-1.amazonaws.com/kusama-api:${COMMIT_HASH}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - lcsproxy
      - default

networks:
  lcsproxy:
    name: lcsnetwork
