version: "3.7"

services:
  substrateapi:
    init: true
    stdin_open: true
    container_name: substrateapi
    tty: true
    image: ${CONTAINER_REPO}/${IMAGE_NAME}:${COMMIT_HASH}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - lcsproxy
      - default

networks:
  lcsproxy:
    name: lcsnetwork
