apiVersion: apps/v1
kind: Deployment
metadata:
  name: substrate-api-deployment
  namespace: default
  labels:
    name: substrate-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: substrate-api
  template:
    metadata:
      name: substrate-api
      labels:
        name: substrate-api
    spec:
      containers:
        - name: substrate-api
          image: $CONTAINER_REPO/$IMAGE_NAME:$COMMIT_HASH
          ports:
            - containerPort: 80
          env:
            - name: LCS_EC2_AWS_ACCESS_KEY_ID
              value: $LCS_EC2_AWS_ACCESS_KEY_ID
            - name: LCS_EC2_AWS_SECRET_ACCESS_KEY
              value: $LCS_EC2_AWS_SECRET_ACCESS_KEY
